### PR TITLE
Add missing points for DDK

### PR DESCRIPTION
**Pull request by connorjcantrell**
Add missing mappings for DDK

### CODE REVIEW

**Comment by connorjcantrell** [comment]
Adding airport ontology mappings to this PR as well

**Comment by connorjcantrell** [comment]
Hi @joebeernink, the tests are failing on the airport related mappings despite merging your test changes into this branch.

**Comment by connorjcantrell** [comment]
@joebeernink Is it possible to look into the cause of the validation test failures for entities belonging to the airport ontology?

**Review by jbkoh — CHANGES_REQUESTED** [review]
Please use Photovoltaic_Array instead of PV_Array. Brick from 1.4 will prefer fully-spelled out versions.

**Review by jbkoh — APPROVED** [review]

**Pull request merged**
